Educational_Website_game/Controllers/IdentifyAreasController.cs
using LibraryDeweyApp.Global;
using LibraryDeweyApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryDeweyApp.Controllers
{
    public class IdentifyAreasController : Controller
    {
        //instantiate all my required objects
        private ApplicationDbContext db = new ApplicationDbContext();
        private Random rand = new Random();
        private Constants con = new Constants();
        private RandomGenerator rg = new RandomGenerator();
        // GET: IndentifyAreas
        public ActionResult Index()
        {
            //using to check if there was a postback
            ViewBag.PostBack = "false";

            return View();
        }

        [HttpPost]
        public ActionResult Index(string y)
        {
            //instantiate model
            MatchColumns mc = new MatchColumns();

            //get length of test from leaderboards
            var leaderboards = db.Leaderboards.Where(p => p.Name.Contains("Identifying")).FirstOrDefault();
            int res = leaderboards.TotalMarks;

            //intialize global list and TimeSpan for timer
            mc.TimeRunning = new TimeSpan(0, 0, 0);

            //assign values to model
            mc.categories = con.Categories;
            mc.TotalResult = res;

            //intialize variables
            Dictionary<int, string> questionsDict = new Dictionary<int, string>();
            int correctAnswers = res;
            int totalCat = con.Categories.Count;
            int totalQuestions = con.maxQuestions;
            int diffBetweenNo = totalCat - totalQuestions;

            //need to first shuffle constant catergories
            //this is to make sure that the first 4 categories are rotated in different orders each time
            Dictionary<int, string> shuffle = mc.categories.OrderBy(x => rand.Next())
            .ToDictionary(item => item.Key, item => item.Value);

            //add to dictionary while loop according to total questions for game
            for (int i = 0; i < shuffle.Count - diffBetweenNo; i++)
            {
                questionsDict.Add(shuffle.ElementAt(i).Key, shuffle.ElementAt(i).Value);
            }
            //create random list of ints for shuffling indexes for questions
            List<int> randNoList = new List<int>();
            randNoList = rg.randomNumberList(0, questionsDict.Count, randNoList, rand);

            //assign dictionary to model
            mc.RandomNoList = randNoList;
            mc.questions = questionsDict;

            //generate random number between 0 - 1
            int randNum = rand.Next(0, 2);
            //check if 0 or 1 to alterante 
            if (randNum == 0)
            {
                //left column = call numbers
                mc.isCallNumberOrder = true;
                ViewBag.ColumnOrder = "Decimal Classes";
                ViewBag.OtherColumn = "Descriptions";
            }
            else
            {
                //left column = descriptions
                mc.isCallNumberOrder = false;
                ViewBag.ColumnOrder = "Descriptions";
                ViewBag.OtherColumn = "Decimal Classes";
            }


            //used to check if HttpPost request
            ViewBag.PostBack = "true";

            return View(mc);
        }
    }
}

Educational_Website_game/Controllers/IdentifyAreasResultController.cs
using LibraryDeweyApp.Global;
using LibraryDeweyApp.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryDeweyApp.Controllers
{
    public class IdentifyAreasResultController : Controller
    {
        // GET: IdentifyAreasResult
        //Instantiate variables
        Global.Constants con = new Global.Constants();
        private ApplicationDbContext db = new ApplicationDbContext();

        [HttpGet]
        public ActionResult Index()
        {
            //get model through tempdata
            MatchColumns mc = TempData["model"] as MatchColumns;
            if (mc != null)
            {
                //total mark allocation
                ViewBag.TotalMarks = 4;
                //percentage value
                double res = (Convert.ToDouble(mc.Result) / Convert.ToDouble(mc.questions.Count())) * 100;
                ViewBag.Percent = res;
            }

            return View(mc);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(MatchColumns mc, string questions, string orgAnswers, string answers)
        {

            //see if the user submitted anything
            if (!string.IsNullOrEmpty(answers))
            {
                //instantiate model paramaters 
                mc.answers = new Dictionary<int, string>();
                mc.questions = new Dictionary<int, string>();
                //split hidden fields to list<string>
                List<string> questionsList = questions.Split(',').Select(sValue => sValue.Trim()).ToList();
                List<string> originalAnswers = orgAnswers.Split(',').Select(sValue => sValue.Trim()).ToList();
                List<string> userAnswers = answers.Split(',').Select(sValue => sValue.Trim()).ToList();

                //create new dictionary answers 
                Dictionary<int, string> userAnswersDict = new Dictionary<int, string>();
                //intialize totalCorrect aswers from model
                int correctAnswers = mc.TotalResult;
                ViewBag.TotalMarks = correctAnswers;

                //loop through questions, answers and original answers to store to model
                //for next view
                for (int i = 0; i < questionsList.Count; i++)
                {
                    string item = questionsList[i].ToString();

                    if (i < correctAnswers + 1)
                    {
                        for (int j = i; j < userAnswers.Count;)
                        {
                            string ans = userAnswers[i].ToString();
                            //need to check if form collection is call number or description
                            if (mc.isCallNumberOrder == true)
                            {
                                //call number in left column
                                //item = call number 
                                userAnswersDict.Add(Convert.ToInt32(item), ans);
                                mc.answers.Add(Convert.ToInt32(item), ans);
                            }
                            else
                            {
                                //description in left column
                                //item = description
                                userAnswersDict.Add(Convert.ToInt32(ans), item);
                                mc.answers.Add(Convert.ToInt32(ans), item);
                            }
                            break;
                        }

                        //loop through orginal answers to add to model
                        for (int k = i; k < originalAnswers.Count;)
                        {
                            string org = originalAnswers[k].ToString();

                            if (mc.isCallNumberOrder == true)
                            {
                                //call number in left column
                                //item = call number 
                                mc.questions.Add(Convert.ToInt32(item), org);
                            }
                            else
                            {
                                //description in left column
                                //item = description
                                mc.questions.Add(Convert.ToInt32(org), item);
                            }
                            break;
                        }
                    }
                    else { break; }                           
                }

                //assign categories to model
                mc.categories = con.Categories;

                //still need to compare dictionaries for result
                //use linq to get values matching
                var matchingDict = mc.answers.Where(entry => mc.categories[entry.Key] == entry.Value)
                 .ToDictionary(entry => entry.Key, entry => entry.Value);

                //count total matching in new dictionary for result
                mc.Result = matchingDict.Count;
                double res = (Convert.ToDouble(mc.Result) / Convert.ToDouble(correctAnswers)) * 100;
                ViewBag.Percent = res;

                //need to get correct answers for left column
                //and store to sortedQuestions
                Dictionary<int, string> CorrectAnswerDict = new Dictionary<int, string>();

                for (int i = 0; i < mc.questions.Count; i++)
                {
                    //variables for easy access and typing
                    int qKey = mc.questions.ElementAt(i).Key;
                    string qValue = mc.questions.ElementAt(i).Value;

                    for (int j = 0; j < mc.categories.Count; j++)
                    {
                        //variables for easy access and 
                        int cKey = mc.categories.ElementAt(j).Key;
                        string cValue = mc.categories.ElementAt(j).Value;

                        //check if left column = description / callnumber using model
                        if (mc.isCallNumberOrder == true)
                        {
                            if (qKey == cKey)
                            {
                                //call number is question
                                CorrectAnswerDict.Add(qKey, cValue);
                                break;
                            }
                        }
                        else
                        {
                            if (qValue == cValue)
                            {
                                //description is question
                                CorrectAnswerDict.Add(cKey, cValue);
                                break;
                            }
                        }                 
                    }
                }

                //assign correct answer
                mc.sortedQuestions = CorrectAnswerDict;

                //may use for future reference below
                //var matches = mc.questions.Keys.Intersect(mc.categories.Keys);
                //foreach (var m in matches)
                //    ResultDictionary.Add(Convert.ToInt32(mc.questions[m]), mc.categories[m]);

                //assign model to tempdata as it is easier than using hidden fields
                TempData["IdentifyModel"] = mc;

                return View(mc);
            }
           

            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult Save()
        {
            //get model from tempdata[]
            MatchColumns mc = TempData["IdentifyModel"] as MatchColumns;
            //check if user entered any answers
            if (!string.IsNullOrEmpty(Convert.ToString(mc.Result)))
            {
                //instantiate model
                Results result = new Results();

                //get Leaderboard for current game
                var leaderboards = db.Leaderboards.Where(p => p.Name.Contains("Identifying")).FirstOrDefault();

                //assign model values
                result.UserID = HttpContext.User.Identity.GetUserId();
                result.LeaderboardsID = leaderboards.LeaderboardsID;
                result.result = mc.Result;
                result.DateCompleted = DateTime.Now;
                result.TimeCompleted = mc.TimeCompleted;

                db.Results.Add(result);

                var dbResult = db.SaveChanges();

                mc.SavedResult = true;

                //check if db was successful
                if (dbResult > 0)
                {
                    TempData["SaveResult"] = $"Your Results were saved successfully on {DateTime.Now} !";
                    //ViewBag.Success = $"Your Results were saved successfully on {DateTime.Now} !";
                }
                else
                {
                    TempData["SaveResult"] = $"You dont have any results to save";
                }
            }

            //assign model to new tempdata
            TempData["model"] = mc;

            return RedirectToAction("Index");
        }

    }
}

Educational_Website_game/Controllers/ReplacingBooksController.cs
using LibraryDeweyApp.Global;
using LibraryDeweyApp.Helpers;
using LibraryDeweyApp.Models;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace LibraryDeweyApp.Controllers
{
    public class ReplacingBooksController : Controller
    {
        //instantiate all my required objects
        private ApplicationDbContext db = new ApplicationDbContext();
        private RandomGenerator rg = new RandomGenerator();
        private Random rand = new Random();
        private Constants con = new Constants();

        // GET: ReplacingBooks
        public ActionResult Index()
        {
            //using to check if there was a postback
            ViewBag.PostBack = "false";

            return View();
        }

        [HttpPost]
        public ActionResult Index(string x)
        {
            CallNumbers cn = new CallNumbers();
            
            //get length of test from leaderboards
            var leaderboards = db.Leaderboards.Where(p => p.Name.Contains("Replacing")).FirstOrDefault();
            int res = leaderboards.TotalMarks;

            //intialize global list and TimeSpan for timer
            cn.RandomCallNumberList = new List<RandomCallNumbers>();
            cn.TimeRunning = new TimeSpan(0,0,0);

            //loop through total marks to display appropiate amount of random cn
            for (int i = 0; i < res; i++)
            {
                RandomCallNumbers rcn = new RandomCallNumbers();
                //call RandomGenerator to get random cn
                string randCallNum = rg.randCallNum(rand, con);
                rcn.ID = i + 1;
                rcn.RandCallNumber = randCallNum;
                //add randcn to global list
                cn.RandomCallNumberList.Add(rcn);
            }

            //used to check if HttpPost request
            ViewBag.PostBack = "true";

            return View(cn);
        }

   

    }
}

Educational_Website_game/Views/IdentifyAreasResult/Save.cshtml
@{
    ViewBag.Title = "Save";
}

<h2>Save</h2>

Educational_Website_game/Views/IdentifyAreasResult/index.cshtml
@model LibraryDeweyApp.Models.MatchColumns
@{
    ViewBag.Title = "Identifying Areas Result";
    var userAnswers = "";
}

<h2>@ViewBag.Title</h2>

@if (TempData["SaveResult"] != null)
{
    <div class="alert-success">
        <strong>@TempData["SaveResult"].ToString()</strong>
    </div>
}

@if (Model != null && Model.questions != null)
{
    <div class="col-md-4">
        <h3>Your score: @Model.Result/@ViewBag.TotalMarks</h3>
        <p> @ViewBag.Percent%</p>
    </div>
    <div class="col-md-4">
        <h3>
            Time: @Model.TimeCompleted
        </h3>
        <p>Date: @DateTime.Now</p>
    </div>



    using (Html.BeginForm("Save", "IdentifyAreasResult", FormMethod.Post))
    {
        //Html.AntiForgeryToken();
        <div class="col-md-4">
            <h3>
                <a class="btn btn-primary" href="~/IdentifyAreas/">Try Again »</a>

                @Html.HiddenFor(a => a.TimeCompleted)
                @Html.HiddenFor(a => a.Result)

                @*<input type="hidden" value="@ViewBag.Result" name="userResult" />*@

                @if (User.Identity.IsAuthenticated)
                {
                    if (Model.SavedResult != true)
                    {
                        <input type="submit" class="btn btn-success" value="Save" />
                    }
                    else
                    {
                        @Html.ActionLink("View Leaderboard", "Results", "Leaderboards", new { id = 2 }, new { @class = "btn btn-success" })
                    }
                }
                else
                {
                    @Html.ActionLink("Log in to Save Next Result", "Login", "Account", new { ReturnUrl = "~/IdentifyAreas/" }, new { @class = "btn btn-success" })
                }
            </h3>
        </div>


        <table class="table table-bordered">
            <tr>
                <th>
                    Questions
                </th>
                @*<th>
                    Answers
                </th>*@
                <th>
                    Correct Answers
                </th>
                <th>
                    Your Answers (@Model.Result/@ViewBag.TotalMarks)
                    @for (int i = 0; i < Model.answers.Count; i++)
                    {

                        //var key = Model.answers.ElementAt(i).Key.ToString();
                        //if (!string.IsNullOrEmpty(userAnswers))
                        //{

                        //}
                        //else
                        //{
                        //    userAnswers = Model.answers.ElementAt(i).Key.ToString();
                        //}
                    }

                </th>
            </tr>
            @for (int i = 0; i < Model.questions.Count; i++)
            {

                for (int j = i; j < Model.sortedQuestions.Count;)
                {
                    for (int k = i; k < Model.answers.Count;)
                    {
                        var qKey = Model.questions.ElementAt(i).Key.ToString().PadLeft(3, '0');
                        var qValue = Model.questions.ElementAt(i).Value;
                        var sortKey = Model.sortedQuestions.ElementAt(i).Key.ToString().PadLeft(3, '0');
                        var sortValue = Model.sortedQuestions.ElementAt(i).Value;
                        var userKey = Model.answers.ElementAt(i).Key.ToString().PadLeft(3, '0');
                        var userValue = Model.answers.ElementAt(i).Value;

                        var questions = "";
                        var answers = "";
                        var correctAnswers = "";
                        var userAnsw = "";

                        <tr>
                             @if (i <= 4)
                             {
                                     //need to check if callnumber = left
                                     if (Model.isCallNumberOrder == true)
                                     {

                                          questions = qKey;
                                          answers = qValue;
                                          correctAnswers = sortValue;
                                          userAnsw = userValue;
                                     }
                                     else
                                     {

                                          questions = qValue;
                                          answers = qKey;
                                          correctAnswers = sortKey;
                                          userAnsw = userKey;
                                     }
                                    <td>
                                        @*@Html.HiddenFor(x => x.RandomCallNumberList[i].ID)
                                        @Html.HiddenFor(x => x.RandomCallNumberList[i].RandCallNumber)*@
                                        <p>@questions</p>
                                    </td>       
                                    <!--<td>-->
                                        @* original answers *@
                                        <!--<p>@answers</p>
                                    </td>-->  
                                    <td style="background-color:#9fff9f;">
                                        @*@Html.HiddenFor(x => x.SortedCallNumberList[i].ID)
                                        @Html.HiddenFor(x => x.SortedCallNumberList[i].SortedCallNumber)*@
                                        <p>@correctAnswers</p>
                                    </td>
                                    @*@Html.HiddenFor(x => x.UserCallNumberList[i].ID)
                                    @Html.HiddenFor(x => x.UserCallNumberList[i].UserCallNumber)*@
                                    if (userAnsw == correctAnswers)
                                    {
                                        <td style="background-color:#9fff9f;">
                                            <p>@userAnsw</p>
                                        </td>
                                    }
                                    else
                                    {
                                        <td style="background-color: #ff9f9f;">
                                            @if (!String.IsNullOrEmpty(userAnsw))
                                            {
                                                <p>@userAnsw</p>
                                            }
                                            else
                                            {
                                                <p>No Answer</p>
                                            }

                                        </td>
                                    }
                             }
                           
                        </tr>
                        break;
                    }
                    break;
                }

            }
        </table>
    }


    if (!string.IsNullOrEmpty(ViewBag.SaveResult))
    {
        <p>@ViewBag.SaveResult</p>
    }
}
else
{
    <div class="col-md-12">
        @if (!string.IsNullOrEmpty(ViewBag.AuthError))
        {
            <h4>You need to login to Save Results</h4>
        }
        @if (!string.IsNullOrEmpty(ViewBag.SaveResult))
        {
            <p>@ViewBag.SaveResult</p>
        }
        <p>You have no results, please try again</p>
        <div class="row">
            @using (Html.BeginForm("Index", "IdentifyAreas", FormMethod.Get))
            {
                @*@Html.AntiForgeryToken()*@
                <input type="hidden" value="start" name="x" />
                <input type="submit" value="Take Test »" class="btn btn-success" />
            }
            @*@Html.ActionLink("Take Test »", "Index", "ReplacingBooks", null, new { @class = "btn btn-success" })*@
            @Html.ActionLink("View Leadorboards", "Results", "Leaderboards", new { id = 2 }, new { @class = "btn btn-primary" })
        </div>
    </div>
}