Educational_Website_game/Controllers/ReplacingBooksController.cs
using LibraryDeweyApp.Global;
using LibraryDeweyApp.Helpers;
using LibraryDeweyApp.Models;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace LibraryDeweyApp.Controllers
{
    public class ReplacingBooksController : Controller
    {
        //instantiate all my required objects
        private ApplicationDbContext db = new ApplicationDbContext();
        private RandomGenerator rg = new RandomGenerator();
        private Random rand = new Random();
        private Constants con = new Constants();

        // GET: ReplacingBooks
        public ActionResult Index()
        {
            //using to check if there was a postback
            ViewBag.PostBack = "false";

            return View();
        }

        [HttpPost]
        public ActionResult Index(string x)
        {
            CallNumbers cn = new CallNumbers();
            
            //get length of test from leaderboards
            var leaderboards = db.Leaderboards.Where(p => p.Name.Contains("Replacing")).FirstOrDefault();
            int res = leaderboards.TotalMarks;

            //intialize global list and TimeSpan for timer
            cn.RandomCallNumberList = new List<RandomCallNumbers>();
            cn.TimeRunning = new TimeSpan(0,0,0);

            //loop through total marks to display appropiate amount of random cn
            for (int i = 0; i < res; i++)
            {
                RandomCallNumbers rcn = new RandomCallNumbers();
                //call RandomGenerator to get random cn
                string randCallNum = rg.randCallNum(rand, con);
                rcn.ID = i + 1;
                rcn.RandCallNumber = randCallNum;
                //add randcn to global list
                cn.RandomCallNumberList.Add(rcn);
            }

            //used to check if HttpPost request
            ViewBag.PostBack = "true";

            return View(cn);
        }

   

    }
}

Educational_Website_game/Controllers/ReplacingBooksResultController.cs
using LibraryDeweyApp.Global;
using LibraryDeweyApp.Helpers;
using LibraryDeweyApp.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryDeweyApp.Controllers
{
    public class ReplacingBooksResultController : Controller
    {
        //instatiate context
        private ApplicationDbContext db = new ApplicationDbContext();
        [HttpGet]
        public ActionResult Index()
        {
            CallNumbers cn = TempData["model"] as CallNumbers;
            if (cn != null)
            {
                //return total matching values by counting matched values in new list
                int totalMatched = cn.MatchedCallNumbersList.Count();
                //total mark allocation
                ViewBag.TotalMarks = cn.SortedCallNumberList.Count();
                //percentage value
                double res = (Convert.ToDouble(totalMatched) / Convert.ToDouble(cn.SortedCallNumberList.Count())) * 100;
                ViewBag.Percent = res;
            }
            return View(cn);
        }
        // GET: ReplacingBooksResult
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(CallNumbers cn, string answers)
        {

            //see if the user submitted anything
            if (!string.IsNullOrEmpty(answers))
            {
                int totalMatched = 0;
               
                LinqSort sort = new LinqSort();
                //now sort the list and compare
                List<string> randList = new List<string>();
                List<string> sortedList = new List<string>();

                //add cn.RandomCallNumberList call numbers to list<string> 
                foreach (var item in cn.RandomCallNumberList)
                {
                    randList.Add(item.RandCallNumber);
                }

                sortedList = sort.ReturnSortedList(randList);

                //split user's ansers and assign to list
                List<string> userAnswers = answers.Split(',').Select(sValue => sValue.Trim()).ToList();

                //initialize model lists
                cn.SortedCallNumberList = new List<SortedCallNumbers>();
                cn.UserCallNumberList = new List<UserCallNumbers>();
                cn.MatchedCallNumbersList = new List<MatchedCallNumbers>();

                for (int i = 0; i < sortedList.Count; i++)
                {
                    for (int j = i; j < userAnswers.Count;)
                    {
                        //used for id
                        int count = i + 1;

                        SortedCallNumbers scn = new SortedCallNumbers();
                        scn.ID = count;
                        scn.SortedCallNumber = sortedList[i];
                        cn.SortedCallNumberList.Add(scn);

                        UserCallNumbers ucn = new UserCallNumbers();
                        ucn.ID = count;
                        ucn.UserCallNumber = userAnswers[j];
                        cn.UserCallNumberList.Add(ucn);

                        break;
                    }          
                }



                //compare the sorted list and user answers
                MatchingLists ml = new MatchingLists();
                List<string> temp = new List<string>();
                temp = ml.MatchLists(sortedList, userAnswers);
                for (int i = 0; i < temp.Count; i++)
                {
                    MatchedCallNumbers mcn = new MatchedCallNumbers();
                    mcn.ID = i + 1;
                    mcn.MatchedCallNumber = temp[i];
                    cn.MatchedCallNumbersList.Add(mcn);
                }
                //cn.MatchedList = ml.MatchLists(sortedList, userAnswers);

                //return total matching values by counting matched values in new list
                totalMatched = cn.MatchedCallNumbersList.Count();

                //display results
                cn.Result = totalMatched;
                //total mark allocation
                ViewBag.TotalMarks = cn.SortedCallNumberList.Count();
                //percentage value
                double res = (Convert.ToDouble(totalMatched) / Convert.ToDouble(cn.SortedCallNumberList.Count())) * 100;
                ViewBag.Percent = res;
            }
            else
            {
                //asign viewbag for error?
                return RedirectToAction("Index");
            }

            //if (TempData["SaveResult"] != null)
            //{
            //    ViewBag.SaveResult = TempData["SaveResult"].ToString();
            //}
          
            return View(cn);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Save(CallNumbers cn)
        {
            //check if user entered any answers
            if (!string.IsNullOrEmpty(Convert.ToString(cn.Result)))
            {
                //instantiate model
                Results result = new Results();

                //get Leaderboard for current game
                var leaderboards = db.Leaderboards.Where(p => p.Name.Contains("Replacing")).FirstOrDefault();

                //assign model values
                result.UserID = HttpContext.User.Identity.GetUserId();
                result.LeaderboardsID = leaderboards.LeaderboardsID;
                result.result = cn.Result;
                result.DateCompleted = DateTime.Now;
                result.TimeCompleted = cn.TimeCompleted;

                db.Results.Add(result);

                var dbResult = db.SaveChanges();

                cn.SavedResult = true;

                //check if db was successful
                if (dbResult > 0)
                {
                    TempData["SaveResult"] = $"Your Results were saved successfully on {DateTime.Now} !";
                    //ViewBag.Success = $"Your Results were saved successfully on {DateTime.Now} !";
                }
                else
                {
                    TempData["SaveResult"] = $"You dont have any results to save";
                }
            }

            TempData["model"] = cn;

            return RedirectToAction("Index");
            //return View();
        }
    }
}

Educational_Website_game/Views/ReplacingBooksResult/Index.cshtml
@model LibraryDeweyApp.Global.CallNumbers
@{
    ViewBag.Title = "Replacing Books Result";
}

<h2>@ViewBag.Title</h2>

@if (TempData["SaveResult"] != null)
{
    <div class="alert-success">
        <strong>@TempData["SaveResult"].ToString()</strong>
    </div>
}

@if (Model != null && Model.RandomCallNumberList != null)
{
    <div class="col-md-4">
        <h3>Your score: @Model.Result/@ViewBag.TotalMarks</h3>
        <p> @ViewBag.Percent%</p>
    </div>
    <div class="col-md-4">
        <h3>
            Time: @Model.TimeCompleted
        </h3>
        <p>Date: @DateTime.Now</p>
    </div>



    using (Html.BeginForm("Save", "ReplacingBooksResult", FormMethod.Post))
    {
        //Html.AntiForgeryToken();
        <div class="col-md-4">
            <h3>
                <a class="btn btn-primary" href="~/ReplacingBooks/">Try Again »</a>

                @Html.HiddenFor(a => a.TimeCompleted)
                @Html.HiddenFor(a => a.Result)

                @*<input type="hidden" value="@ViewBag.Result" name="userResult" />*@

                @if (User.Identity.IsAuthenticated)
                {
                    if (Model.SavedResult != true)
                    {
                        <input type="submit" class="btn btn-success" value="Save" />
                    }
                    else
                    {
                        @Html.ActionLink("View Leaderboard", "Results", "Leaderboards", new { id = 1}, new { @class = "btn btn-success" })
                    }
                }
                else
                {
                    @Html.ActionLink("Log in to Save Next Result", "Login", "Account", new { ReturnUrl = "~/ReplacingBooks/" }, new { @class = "btn btn-success" })
                }
            </h3>
        </div>


        <table class="table table-bordered">
            <tr>
                <th>
                    Random List
                </th>
                <th>
                    Correct Order
                </th>
                <th>
                    Your Answers (@Model.Result/@ViewBag.TotalMarks)
                    @for (int l = 0; l < Model.MatchedCallNumbersList.Count; l++)
                    {
                        @Html.HiddenFor(m => m.MatchedCallNumbersList[l].ID);
                        @Html.HiddenFor(m => m.MatchedCallNumbersList[l].MatchedCallNumber);
                    }

                </th>
            </tr>
            @for (int i = 0; i < Model.RandomCallNumberList.Count; i++)
            {
                for (int j = i; j < Model.SortedCallNumberList.Count;)
                {
                    for (int k = i; k < Model.UserCallNumberList.Count;)
                    {
                        var sort = @Model.SortedCallNumberList[i].SortedCallNumber;
                        var user = @Model.UserCallNumberList[i].UserCallNumber;
                        <tr>
                            <td>
                                @Html.HiddenFor(x => x.RandomCallNumberList[i].ID)
                                @Html.HiddenFor(x => x.RandomCallNumberList[i].RandCallNumber)
                                <p>@Model.RandomCallNumberList[i].RandCallNumber</p>
                            </td>
                            <td style="background-color:#9fff9f;">
                                @Html.HiddenFor(x => x.SortedCallNumberList[i].ID)
                                @Html.HiddenFor(x => x.SortedCallNumberList[i].SortedCallNumber)
                                <p>@sort</p>
                            </td>
                            @Html.HiddenFor(x => x.UserCallNumberList[i].ID)
                            @Html.HiddenFor(x => x.UserCallNumberList[i].UserCallNumber)
                            @if (user == sort)
                            {
                                <td style="background-color:#9fff9f;">
                                    <p>@user</p>
                                </td>
                            }
                            else
                            {
                                <td style="background-color: #ff9f9f;">
                                    @if (!String.IsNullOrEmpty(user))
                                    {
                                        <p>@user</p>
                                    }
                                    else
                                    {
                                        <p>No Answer</p>
                                    }

                                </td>
                            }
                        </tr>
                        break;
                    }
                    break;
                }

            }
        </table>
    }


    if (!string.IsNullOrEmpty(ViewBag.SaveResult))
    {
        <p>@ViewBag.SaveResult</p>
    }
}
else
{
    <div class="col-md-12">
        @if (!string.IsNullOrEmpty(ViewBag.AuthError))
        {
            <h4>You need to login to Save Results</h4>
        }
        @if (!string.IsNullOrEmpty(ViewBag.SaveResult))
        {
            <p>@ViewBag.SaveResult</p>
        }
        <p>You have no results, please try again</p>
        <div class="row">
            @using (Html.BeginForm("Index", "ReplacingBooks", FormMethod.Post))
            {
                @*@Html.AntiForgeryToken()*@
                <input type="hidden" value="start" name="x" />
                <input type="submit" value="Take Test »" class="btn btn-success" />
            }
            @*@Html.ActionLink("Take Test »", "Index", "ReplacingBooks", null, new { @class = "btn btn-success" })*@
            @Html.ActionLink("View Leadorboards", "Results", "Leaderboards", new { id = 1 }, new { @class = "btn btn-primary" })
        </div>
    </div>
}

Educational_Website_game/Views/ReplacingBooksResult/Save.cshtml
@{
    ViewBag.Title = "save";
}

<h2>save</h2>

@if (!string.IsNullOrEmpty(ViewBag.Success))
{
    <p>@ViewBag.Success</p>
    @*<a class="btn btn-default" href="~/ReplacingBooks/">Try Again »</a>*@
}
else
{
    <p>You don't have any results to save, or it was unssuccesful</p>
}

@Html.ActionLink("Try Again »", "Index", "ReplacingBooks", null, new { @class = "btn btn-success" })
@Html.ActionLink("View Leadorboards", "Results", "Leaderboards", new { id = 1 }, new { @class = "btn btn-primary" })